# Generated by Django 2.0.6 on 2018-11-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_follows'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_type',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
